CREATE TABLE IF NOT EXISTS posts(
   name        VARCHAR(64) NOT NULL
  ,rating_total INTEGER  NOT NULL
  ,rating_score NUMERIC(3,1) NOT NULL
  ,image_url   VARCHAR(255) NOT NULL
  ,location     VARCHAR(32) NOT NULL
  ,location_url   VARCHAR(255) NOT NULL
);
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Mount Leuser National Park',189,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQNv9uvapMWyIUNeRCB_sGmy6WTZCCdqEcinGC9pKHkiEWF9ZYGhIcL6RieFYTVp4JrdxrimYwDfTxDeCQ2BFTedg','aceh','https://www.google.com/maps/search/?api=1&query=mount+leuser+national+park'),
	 ('Baiturrahman Grand Mosque',23409,4.8,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR-9fGNjaYtpQUfz68YBjlqZ6IHzPly78MoDrUSKA66SWQrD3MgCP0d8peP9BcRjNbaP0WTFeVvc3YD4NA8sL3nmg','aceh','https://www.google.com/maps/search/?api=1&query=baiturrahman+grand+mosque'),
	 ('Museum Tsunami Aceh',9833,4.6,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTQwckGYH-AouvA0vec5e4qFa5nJ48xYjSWd2j8cSKKnMzgxIoBBMnB-00SkBI2ejMWvxQv6XAgWBhWZx3IBuSkLg','aceh','https://www.google.com/maps/search/?api=1&query=museum+tsunami+aceh'),
	 ('Iboih Beach',2355,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcShP5hK1Kz8Hhj-4b4Qn0kClU4zVFOIPcxK9-50Zstc6eQBxibmlcemxvr0zCPW9XdVm2y_kmSPwR6uhx3zSVxaMw','aceh','https://www.google.com/maps/search/?api=1&query=iboih+beach'),
	 ('Lampuuk Beach',1873,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQwdmlrodOZiTx08u3gKh7eCc7O6K2ts1HUNpqD5E1HY8JRTbiCNDYRD46z7QrM3qXNFYDHpzuTinl9luhzRM72lw','aceh','https://www.google.com/maps/search/?api=1&query=lampuuk+beach'),
	 ('Sumur Tiga Beach',952,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTkzZ0EbUai9ozddyNMrIpW3ccnFcGxyn77HXHM_PPfKmk2NpseIoAZcmJcUIq-Ll9ugFayzduFjYx5UIr1G-wR6Q','aceh','https://www.google.com/maps/search/?api=1&query=sumur+tiga+beach'),
	 ('Istana Maimun',17525,4.4,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT3fBfPLPqBBU2_8krbiiualiXx2OBPkTUGr-HCEFs7k8rOdxoN_erSmjceZpC-eszoGw6iBkZaOFE3Mjl7DDu80w','sumatera+utara','https://www.google.com/maps/search/?api=1&query=istana+maimun'),
	 ('Air Terjun Sipiso Piso',2420,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRYmIzeqhk5hr6b43Q6g6t1wyZZUkAuMzBn3uvsFgg327IRkKWDK214-6F7OQwwTtlucke6wHsaiznOIcAceGREIA','sumatera+utara','https://www.google.com/maps/search/?api=1&query=air+terjun+sipiso+piso'),
	 ('Mount Sibayak',467,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQ1UpEzNgLmbQ31ci2DEFb3SULb2fg6lijWxYfly829p5ebjaO043gBd4AvCPv1F75WKs7PCerBtZtHEChTaZDJrg','sumatera+utara','https://www.google.com/maps/search/?api=1&query=mount+sibayak'),
	 ('Masjid Raya Al-Mashun Medan',397,4.8,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQfjOB1i_8zW_zVwLbnq3DFpp2iDd5xyLgb9fYM3O_Ow52IwBCH2U_GEfNhzcDHfIwdLPvqijMtRoxHFKOtAh94wQ','sumatera+utara','https://www.google.com/maps/search/?api=1&query=masjid+raya+al-mashun+medan');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Mount Sinabung',979,4.3,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQCTJQMBl7z4oyA_TZxwy94YysLicQh22-stip1uWDEcubZeVjzbHFd9Buk7zQ7NYhEjWXlhKNtt_xlWXJvoQb-iA','sumatera+utara','https://www.google.com/maps/search/?api=1&query=mount+sinabung'),
	 ('Tjong A Fie Mansion',2621,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQcNf8cooDZlTEre0qjtWZFQfTPD8_UEn7fVVn5S_tP0huCFNVxyz7S4BESZE8KMt0Dk50uiv_AgtHVkntOI2Z4NA','sumatera+utara','https://www.google.com/maps/search/?api=1&query=tjong+a+fie+mansion'),
	 ('Mount Kerinci',694,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQpeD1qrC7Ph7coh9C2_mJgtC-TIX0vqVXrAy1YkpZOHFb1_CenLN2IohcmMFk01tFoLJGm6Fe7tk7CPrHmQe869w','sumatera+barat','https://www.google.com/maps/search/?api=1&query=mount+kerinci'),
	 ('Lake Maninjau',1136,4.6,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDM5t4lj7JLwo7nK_W8i1WujvCQqnR14ZCrGwOfBOoBE7h9f2SxPG-mx0AgSU3WvB5VLx_BQZkLvpQEQRxJoc3pA','sumatera+barat','https://www.google.com/maps/search/?api=1&query=lake+maninjau'),
	 ('Pantai Air Manis',1954,4.2,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcT4wmrLaax3QJnpH0z5kbzIpJHbA_ujPKD8P4gZ4X9UyIJRYXJBUpJN1eW1Qko05gbclgKTdScgRufBmBcr_k2iUA','sumatera+barat','https://www.google.com/maps/search/?api=1&query=pantai+air+manis'),
	 ('Istano Basa Pagaruyung',13709,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRNkRUTLER0BwQ_TLN7efQgni1hjMihZKSfHBJFauPQ3R-kTTWdVyPcQFWUppnMChIKm1s6DqSBO28uAy3dMBUs8A','sumatera+barat','https://www.google.com/maps/search/?api=1&query=istano+basa+pagaruyung'),
	 ('Lake Singkarak',1484,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRybnAlz37joEKODVwvtCPGr0KD0eW7u1c4KvHa3qdC2ZJVEfaR1SyIXlvsg-6pW1bl0auVmr8bxcWHgMRcAQVNdw','sumatera+barat','https://www.google.com/maps/search/?api=1&query=lake+singkarak'),
	 ('Jam Gadang Bukittinggi',47335,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTLQpJL9YPuUFIgiRb-F2tVoY8fLvjHJlMxbdifNXDtWpBr5EeyS3EiGIZBLgcAqUYk2q3mH9MZR7b-_rurPb6YKg','sumatera+barat','https://www.google.com/maps/search/?api=1&query=jam+gadang+bukittinggi'),
	 ('Muara Takus Temple',942,4.3,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR94-8JubFQu3GI4OFF268-rCR1SKU57LMzSjt51oL5TdTvw4FDN3gvctBlhrSv_9o8i-HXeD8MEGpjPmVHxJH73w','riau','https://www.google.com/maps/search/?api=1&query=muara+takus+temple'),
	 ('Siak Sri Indrapura Palace',7523,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQdbJPkUxY5IevZJfL6XviUrmyhKA4B_XYEWzYlVf33S3qmWJ-PC5xYInwtVHMFIKY3nlVB-ten8K2L8xHe0aROEg','riau','https://www.google.com/maps/search/?api=1&query=siak+sri+indrapura+palace');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Ulu Kasok',2107,4.2,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTP3HZ9Wy6fHUSu_3gIewDwoPi7hN_soe1PZl1IfNp7VFZLNel8sKjy8BR_KuNbUBZ1jIT6Sn6lUZo3ASWeI-6pdw','riau','https://www.google.com/maps/search/?api=1&query=ulu+kasok'),
	 ('Masjid Raya An Nur Riau Province',7676,4.8,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTlWAR87Qn1a1-fcimHLR3eDha2fLkPrUoHj-DgSY1DLaAohvOS_zxWVMcGVRHfRlnidDzz_rr4VF1B4Gvbuep-Qg','riau','https://www.google.com/maps/search/?api=1&query=masjid+raya+an+nur+riau+province'),
	 ('Jalan Alam Mayang',36,4.4,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT_at00F9SPRzR3bDM6V-IBJJedZ1f4ZV20sSQi8eOdlWQtv8EebGixcXEc9p_sOOp7NIMNw13VQfRnrg','riau','https://www.google.com/maps/search/?api=1&query=jalan+alam+mayang'),
	 ('Kebun Binatang Kasang Kulim',1448,4.0,'https://lh5.googleusercontent.com/p/AF1QipPA__fLzFFZLkZK4USuCoWafsmsXFGcCWrD2mnK=w464-h260-n-k-no','riau','https://www.google.com/maps/search/?api=1&query=kebun+binatang+kasang+kulim'),
	 ('Trikora Beach',213,4.4,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQXfaeCbSirUzpH3dvyoOCrQZVyREFGVYKPepE67-YvVof1euh7tV2KMe-ESUcPVIF4g3DUrx90DGwGeJU8lu2KDQ','kepulauan+riau','https://www.google.com/maps/search/?api=1&query=trikora+beach'),
	 ('Penyengat Island',182,4.5,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTjqihQBsFDqzFW_B9_xMTbuCCRPXwPr6ringgIqn0HDL6y2vVyV3F2x5VAURLJY2V1k2ZIlftPyuShR4n_KGAUMg','kepulauan+riau','https://www.google.com/maps/search/?api=1&query=penyengat+island'),
	 ('Ria Bintan Golf Club',73,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcR2H5oXm3PYR1bs5WS86r9JRQOPJo_XXrTfgtJGgl278aiFSGKnAAh93oNXD7tsdmqTjwHwbRx1Py9yTmdmN9zDDw','kepulauan+riau','https://www.google.com/maps/search/?api=1&query=ria+bintan+golf+club'),
	 ('White Sands Island',268,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQwaXbg_8erZFeAAwhFDcCi_0ay9_R9bvElWKlNQBEMti-1EzxSUymllwg2bA8RxxSx_7q6rRTFu7A04qv1YjMBmg','kepulauan+riau','https://www.google.com/maps/search/?api=1&query=white+sands+island'),
	 ('Plaza Lagoi',108,4.4,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAw4ibJJbFMog2_cROjhac-hjnfAGscNSeSsxeQVc7AMu28cCvZ3gAEUPaTBlaT1ji392N5_L0G9AZYQ','kepulauan+riau','https://www.google.com/maps/search/?api=1&query=plaza+lagoi'),
	 ('500 Lohan Temple',41,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSGbyFo8NzXy2IUjm383CVBv5K2lF_Asfi4vib5mZfu4NVRjuNJ3aYIGcDgfJSiW-Fm7DIpBf4P0szBXXPfLKHj7w','kepulauan+riau','https://www.google.com/maps/search/?api=1&query=500+lohan+temple');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Taman Nasional Kerinci Seblat',7,5.0,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSmAIAvmyb9x-9QLxr04eRG7_v_XxkdAlfIDtFH4d5fjUw5oNxTnZX6GkdSqy2cDWUjENNzYOXxTXmZTfydT15CTw','jambi','https://www.google.com/maps/search/?api=1&query=taman+nasional+kerinci+seblat'),
	 ('Lake Kaco',149,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRKXE4TAyTJarHz8zyzBvDTLvGFSRJmPNSoz3J0_QJmjzbQ-etifsc3cKLXW9jQtZDhK8O2aJi5zJvwY6cjemF3ew','jambi','https://www.google.com/maps/search/?api=1&query=lake+kaco'),
	 ('Candi Muaro Jambi',1616,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRVl50yF_9nBB8_GQa1P9868MrcX3HF1imzGRqwwcF4P4JliKuGPIiEshRAqtE12IBdS5LcjbkVYpRCwufTyVUKSA','jambi','https://www.google.com/maps/search/?api=1&query=candi+muaro+jambi'),
	 ('Jambi Paradise',2912,4.1,'https://lh5.googleusercontent.com/p/AF1QipOV5kQgetLwo01SXWoGz2wYfGXEvQJ6_fhvlD_2=w464-h260-n-k-no','jambi','https://www.google.com/maps/search/?api=1&query=jambi+paradise'),
	 ('Berbak National Park',62,4.2,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR4NpqS0N1-UF8a2eaDZDOpRkvadXFaYpCBQyotHolTyqVHSGRh6pZ-xTHgH1Y1CpPvDYXStvUMFIDOdZJeJw2fJg','jambi','https://www.google.com/maps/search/?api=1&query=berbak+national+park'),
	 ('Gentala Arasy Tower',2288,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSW9zXVnTpO57ES933Dn9EnKeUrA7LNgxmf40048-h1Oh4unyrlO0pIZo6J46b1HRAx3u-cOeVfM2YkkErlHoifsA','jambi','https://www.google.com/maps/search/?api=1&query=gentala+arasy+tower'),
	 ('Tanjung Tinggi Beach',4396,4.7,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTLuEMxAwzYJYuOrcgtN7llJ_pdjD8ap1CkZ89WoGJFYyc003R6D1j5YmSsWEQ8hOStBjlgNsktAD75FXMNxwh2HQ','kepulauan+bangka+belitung','https://www.google.com/maps/search/?api=1&query=tanjung+tinggi+beach'),
	 ('Pantai Parai Tenggiri',2071,4.5,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSjysL7EosapiPl8dtwHLFhAOURcLSfyL1qmEnE7BpR_F9EUGrxOBMi9_fLRfu-G2-83Br6MhYYS2e2uw13o33XBg','kepulauan+bangka+belitung','https://www.google.com/maps/search/?api=1&query=pantai+parai+tenggiri'),
	 ('Tanjung Pendam Beach',265,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTYY9ZVfj9HluqNsDWmq-UWXyUjxq3Gl_u7XwQYl19-JQz5tlS3iECRk83CaA5tg0GeAs3v4U1CC1f56UZHp3bF-g','kepulauan+bangka+belitung','https://www.google.com/maps/search/?api=1&query=tanjung+pendam+beach'),
	 ('Kepayang Island',687,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQts_7TrEhoqdTg1itr0zcQ33J4_daICMfxGMplUGjyulrlKSUeoRsncdnLeRQ3VAZ6VyeY9hHGwzI_f6MdOJ_0Kw','kepulauan+bangka+belitung','https://www.google.com/maps/search/?api=1&query=kepayang+island');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Replika SD Muhammadiyah Laskar Pelangi',4139,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTh71S-BB7pRR4cKS8jWSEJMWie0zb1yksjQbEfNGPpGuTWRKp6S2nDFdHu8OvNumaoFvQHIOEg-MQ2AGL0mkMe5A','kepulauan+bangka+belitung','https://www.google.com/maps/search/?api=1&query=replika+sd+muhammadiyah+laskar+pelangi'),
	 ('Pantai Pasir Padi Pangkalpinang',1783,4.3,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQLyhNy9K1wzUv1UnqHjxwMB9e1wcE60J511Ck23pwr6uX6uYVOMNRHjcyh-JiBAt7w9r9RO9--sijC6Zh1mehuDw','kepulauan+bangka+belitung','https://www.google.com/maps/search/?api=1&query=pantai+pasir+padi+pangkalpinang'),
	 ('Panjang Beach',194,4.4,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSwtM5Jg-YMKvkhEYrVEdwWudnL5BzUlDXiEUMY8O2GY_Hx5svl89TBlFtcyYdAHBpBnqzCjXredzmb_MIbyRp-Mg','bengkulu','https://www.google.com/maps/search/?api=1&query=panjang+beach'),
	 ('Benteng Marlborough',8282,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQPwP_V058S0gvvZeA1lvEP7iWlEcSPri5S34BwJTle91hH34ytMUj2JbfVleNmiwdaKqNnYPONGupM-QPDLUOMRA','bengkulu','https://www.google.com/maps/search/?api=1&query=benteng+marlborough'),
	 ('Pantai Panjang Bengkulu',8083,4.4,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcReSIK3CT8OuzQ2jzogNqfnBLSDZSlvxC5Cfk7jCEcGxElvT8OE-NbGbFAkpHxfL7FebJ1Ws0pUVHsiRg','bengkulu','https://www.google.com/maps/search/?api=1&query=pantai+panjang+bengkulu'),
	 ('Pantai Jakat',565,4.2,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcToKA38vUYRPs0nzIk2hO-jlsy2V2xwhvEypLtaGa1HdGZheXXRt4IFXlYN7v1rVsRB2rpoHZKOj3BWEZ0IYUk1lA','bengkulu','https://www.google.com/maps/search/?api=1&query=pantai+jakat'),
	 ('Pantai Tapak Paderi',354,4.4,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ5ailmzAABSHOa1xfPwNBW9xHCjwV6IODPcQZS2To979zNqpUBVfVMG6xeaDIjglye9FUNK8HukNB1PwDyxCZwgQ','bengkulu','https://www.google.com/maps/search/?api=1&query=pantai+tapak+paderi'),
	 ('Dendam Tak Sudah Lake',262,4.2,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSj9hAzgyrBXfECOfLLbnjdUGSXZmZf-jifMbamdYv4hwRoh6KFFdGuS_8lPqgxRRCZ0urUseBGtGgisTj7Ksw8Vw','bengkulu','https://www.google.com/maps/search/?api=1&query=dendam+tak+sudah+lake'),
	 ('Kemaro Island',465,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR2JwbMXh9A0iF0tbuOulPr22uTfGvhjIiz2KCTh_tKmnFM3uwSCbabjJfbjtWHP5vDoLNZfBwnz73BgcjX9vRDbg','sumatera+selatan','https://www.google.com/maps/search/?api=1&query=kemaro+island'),
	 ('Mount Dempo',727,4.6,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQtBZwQSbWvQBbXes9YE1tS3T0L4ta7qig3Uwdm9gsR2CKEgLb-r7B7A6vRCWH6NnkiGJ8CeSr46LOUUciLvqpH4w','sumatera+selatan','https://www.google.com/maps/search/?api=1&query=mount+dempo');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Kuto Besak Fortress',7790,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTWFsN-bMJlbeTbG64DVit6iRNdfUVu_iKfMQCfkcyp1CH84dLqpNlKJjh5Yz8K88E5upO90hHHDntITiq2T3Qdcg','sumatera+selatan','https://www.google.com/maps/search/?api=1&query=kuto+besak+fortress'),
	 ('Taman Wisata Kerajaan Sriwijaya',2885,4.4,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS1x_F30i3Ok4x0azj9GP6ZTK-_hNRe7Y0_cvoU3S-z70VE35BlBKWSOP2AtEplkDhSkTTLpbzAjL6YbsumILQo-Q','sumatera+selatan','https://www.google.com/maps/search/?api=1&query=taman+wisata+kerajaan+sriwijaya'),
	 ('Bukit Siguntang',2341,4.5,'https://lh5.googleusercontent.com/p/AF1QipOjohEOrAEoMiJo345i5kl-YlngRaMo8RHGHw74=w464-h260-n-k-no','sumatera+selatan','https://www.google.com/maps/search/?api=1&query=bukit+siguntang'),
	 ('Sultan Mahmud Badaruddin II Museum',899,4.5,'https://lh5.googleusercontent.com/p/AF1QipPozPRIt9XBedY7y2znB4EXYWymHAksSQlrSdzl=w464-h260-n-k-no','sumatera+selatan','https://www.google.com/maps/search/?api=1&query=sultan+mahmud+badaruddin+ii+museum'),
	 ('Krakatoa',2598,4.1,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQMrUbBEGEV5eQ0ZH9IuUsMosi1jZfkQ2oBRFYOtnwJDhjOism2_0hi4Q2IG-0B6Moj52pFYjzMp9-GwrLn6xmeqQ','lampung','https://www.google.com/maps/search/?api=1&query=krakatoa'),
	 ('Way Kambas National Park',4461,4.3,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQfRML-hpzD030W_LubiSVfEOCCLPKk4oSYW-lvqJT3V6dUMhnYry-F0ZRbAGS7kViIgAJQ3vqqWc3gOyceFbnXxw','lampung','https://www.google.com/maps/search/?api=1&query=way+kambas+national+park'),
	 ('Waduk sangu banyu',3,3.7,'//www.google.com/maps/vt/data=4AdtgTXc-iefxcnXJigx0FQ835IIfF_KZkJN79fziWF3eWpv0WPOKP4NYsRQVRYkOZWu6Q56TwgBOCQ8vAHTroLtZjE5jLssSS6fjvY','lampung','https://www.google.com/maps/search/?api=1&query=waduk+sangu+banyu'),
	 ('Bukit Alam Pujorahayu',8,3.6,'https://lh5.googleusercontent.com/p/AF1QipNjY1nETAYcPLtBIWZ55on9oIvfMrpqLVgG7ehO=w464-h260-n-k-no','lampung','https://www.google.com/maps/search/?api=1&query=bukit+alam+pujorahayu'),
	 ('Air terjun dua putri',12,4.1,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQnwc-UdP0febo9Ar1rc9_r-_lPPApcuXX0VcQzmulDlZYeJkyLmB4U8Y0BLoEBelnzFXhsv92IdFDNMq0GYADiqA','lampung','https://www.google.com/maps/search/?api=1&query=air+terjun+dua+putri'),
	 ('Pantai kamintara',54,4.6,'https://lh5.googleusercontent.com/p/AF1QipP-Harw9AsW6Mvu0Kduu604DFi2jInLuX-sZZrK=w464-h260-n-k-no','lampung','https://www.google.com/maps/search/?api=1&query=pantai+kamintara');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('National Monument',102018,4.6,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQTYZZrqIdYGlgT3rzzGPlS4TY3XmP1hWnSxNPRCfxRYCSm6_p1k21Y9SFeYCPoYfmI-idKucsiJWi7ZRt8iHQr6w','dki+jakarta','https://www.google.com/maps/search/?api=1&query=national+monument'),
	 ('Istiqlal Mosque',8026,4.7,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUJdagDBzQcTJr4UYp0VXIl7sF0B_Up4-J-WQK8PUxE6vhxpnTJJ1ezJyz_I_ghEbDCD55iaDCSwXVqn1XZ2T5w','dki+jakarta','https://www.google.com/maps/search/?api=1&query=istiqlal+mosque'),
	 ('Taman Mini Indonesia Indah',141833,4.5,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQGEGMXts3lh40NicQ86zzkOWsxPqc_OifhkQtf2FAvS-xnNdEw8jhT2bpS95D91AtibW9jngffvy0vbYKdJF-l1A','dki+jakarta','https://www.google.com/maps/search/?api=1&query=taman+mini+indonesia+indah'),
	 ('Museum Nasional Indonesia',11847,4.6,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQes7H6VCWAl2exa6aa0xbrxwJ-VW4NWSusRYV1omoIZz7YUVl61HCan9r0YvWRYawDT_QheXUy7DPzqik6bBCg2A','dki+jakarta','https://www.google.com/maps/search/?api=1&query=museum+nasional+indonesia'),
	 ('Ragunan Zoo',92923,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSmL7mOgAcvzsySSBs90tE6Y3-jUQPcXccUXxWF60CxGj07NoVjxJC0Mde_THtS11UhVdmqCqtMqWlp1C7HrTtn0g','dki+jakarta','https://www.google.com/maps/search/?api=1&query=ragunan+zoo'),
	 ('Taman Impian Jaya Ancol',39866,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQsrUE1Rl-oteT-AJ6-Aqu-vWCgNRtwRjnNciBjqKqxwzAvB-VdR6EUqAOlinybRHGE_3obTQsJ2B3dun86yt0xLQ','dki+jakarta','https://www.google.com/maps/search/?api=1&query=taman+impian+jaya+ancol'),
	 ('Ujung Kulon National Park',3607,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSJIdFIS2Jcqw9g5rSsViRIP3gjqXixvGXCP8fWZSiaygbWOZASsr1-CX12h5gCu4LZ2LeUv1UIcdngHb5x50wagw','banten','https://www.google.com/maps/search/?api=1&query=ujung+kulon+national+park'),
	 ('Tanjung Lesung Beach',1885,4.4,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSn1tCKYOPh14KgniF-J45vpFQvSsE6fD0goXp2ImpyZp1fBRxbvgh5sTRRYzaHHoZ5qXlgc03iFZ9d2labz45vAQ','banten','https://www.google.com/maps/search/?api=1&query=tanjung+lesung+beach'),
	 ('Sawarna Beach',6128,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQF34lfOSj1nNASlGEZuTOfkTXcrbuSIpGi32bjA_Frg1hvoAwX1eoJZ60H8dG_kHdxT30MpLYw5qZhyrDJIDlKkg','banten','https://www.google.com/maps/search/?api=1&query=sawarna+beach'),
	 ('Florida 2 Anyer Beach',3891,4.2,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRJHmitbJMwKf4zxMn5KHhQruJKU8t5rLgEOXxV1rx1z5DDQ27NgzINrmk9D5OFPJriWX75JDN9xwQ5Dsrknj9Etw','banten','https://www.google.com/maps/search/?api=1&query=florida+2+anyer+beach');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Carita Beach',1349,4.3,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTkHHFFtz_hGbU7EQjIkC8QPDX8LjEF8_0QDEO9GDKkrxA2_d2Q0mQw71adQllozxLG3qCJ5EHFne6yk5QLFYNAFQ','banten','https://www.google.com/maps/search/?api=1&query=carita+beach'),
	 ('Peucang Island',135,4.8,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRcNeoQnTdAgRfNxLtYMHS0NyG9iW4jwnoBk38JjYMZCrZsFkMn8Lo2kr0VN3Yu0S-ca1b9x5KdKSSOqgxsKSb0Iw','banten','https://www.google.com/maps/search/?api=1&query=peucang+island'),
	 ('White Crater',5622,4.5,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQdWmZhVkLyHB0Yq_7naGoswH8SQag_ulvUmAewOmWKAARNWYveiO4reN_894LzfzDPoR15oBXP3LTJbyo1VBQkTg','jawa+barat','https://www.google.com/maps/search/?api=1&query=white+crater'),
	 ('Bogor Botanical Gardens',85962,4.7,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTav8LSKdReTBo1s4Hql6EDf_jCzapUH2B8o5NWsDGKfvUa8Wl8HkgX5U_Z4FfORJrg6NK4F_dM60lkd03EDocVDg','jawa+barat','https://www.google.com/maps/search/?api=1&query=bogor+botanical+gardens'),
	 ('Tangkuban Perahu',5264,4.5,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcROT_O8mw8ACPB8KKTSLCh4V7Z_29Vex3dBpWlZwL8egN97Z60lX9SznhiKWeh3tdaNqKFcslX6hlPkg7rOB7f4hw','jawa+barat','https://www.google.com/maps/search/?api=1&query=tangkuban+perahu'),
	 ('Taman Safari Indonesia Bogor',51738,4.6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_se6ZZSfhaINPRKS0hpJvDorSt7x7iYA5LOzOo1lSHV98Phdiy09scX2-njw-5T2dwjLM7bfq703gdQ-v-wiesQ','jawa+barat','https://www.google.com/maps/search/?api=1&query=taman+safari+indonesia+bogor'),
	 ('Puncak',6588,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQCUZFMkQek6ANTKLNKlS86OPMd0ehtCF-qHfnisTy-nag5YcmQde0Z25Jgao15guWf8jNNAxOXV5qory8bdiwj0w','jawa+barat','https://www.google.com/maps/search/?api=1&query=puncak'),
	 ('Jalan Braga',455,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRMn97e-sa5I8eHXeNgtGLQppkC0B7T9McD3PMVebEN9b2ljQtLb0ntWe6p0Ql-768Xff59zou5ckwUnE31qCgpgA','jawa+barat','https://www.google.com/maps/search/?api=1&query=jalan+braga'),
	 ('Borobudur Temple',86348,4.7,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQr14Ju4usDtWgH63fi-IozWikBTSEWpKddwbrEEY0thmTg-_TWtvbjrm5mQ1DHzIwKUU8cm79bNtAAuJLZ7hgpIw','jawa+tengah','https://www.google.com/maps/search/?api=1&query=borobudur+temple'),
	 ('Mount Merapi',2467,4.4,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8Soyr7kiHk23DF0-_EpG5gxsSM1r_3SECiQ8Bm3GoH9o46PTo3hLUuTmnJWxDttaOAyWXHIAf52sR54AaBzrMXw','jawa+tengah','https://www.google.com/maps/search/?api=1&query=mount+merapi');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Dieng Plateau',7180,4.6,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTqYQjBmwUa6dL8W58j9klDcW4QQjtij7GALsMdPB4p0A5PBgybEdn3C-ixrd4cGvquzyQyiHL5LpvVLVDyxEyZ8Q','jawa+tengah','https://www.google.com/maps/search/?api=1&query=dieng+plateau'),
	 ('Lawang Sewu',61689,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSwly-9drgtcBYDzkNAs7f37fzJohSaP8Yb4r5iJaCwIfn3GxG7-7B0ssAH5kn-1jFP0ul_Ppv7BNfK8Gl61WoDCA','jawa+tengah','https://www.google.com/maps/search/?api=1&query=lawang+sewu'),
	 ('Mount Merbabu',2588,4.6,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRMmIUIvv394a_tPkknLs_ppa-oxsg_WsxsLrhNErI_cukmqk1cygcSr-8zZGx8nxKAnOHVBn1N002uYDZ4nP5jrQ','jawa+tengah','https://www.google.com/maps/search/?api=1&query=mount+merbabu'),
	 ('Mount Lawu',2249,4.5,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRjbx9_cziqe2xRbl5xkry5O9eHaDDskHIwQn8eflwZ0RFDBlf8IgRpJ_QAqPZLh6k_K-LXjqbJBWZDuUtO6yO_wg','jawa+tengah','https://www.google.com/maps/search/?api=1&query=mount+lawu'),
	 ('Mount Bromo',9521,4.6,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSj4Y4TUIIdTX44ccU9C6PcjGYMCxfOG9LAf8TfoMyJVztFOntVGRpdAtBCYJPNJiCoUU_Xs4zcl3Ip3gGxku9fIQ','jawa+timur','https://www.google.com/maps/search/?api=1&query=mount+bromo'),
	 ('Ijen',3842,4.7,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRcb34yZH_Q91VWa6zBP-sWEqp5sOV6Zwph9bNiOkXz4sSyTn-YFb1Fi0Vw1Tt_22PcRIZ4LF_iS-aGqM1i79D2Sw','jawa+timur','https://www.google.com/maps/search/?api=1&query=ijen'),
	 ('Semeru',2705,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQkflhDSSscm-h5CxaMjSm6H1KK5UI3md08VZx9QqCvAeV-B6z8GIxfa_gPwh99LGHyDeUG6W2e2ccmj7wMttj-wg','jawa+timur','https://www.google.com/maps/search/?api=1&query=semeru'),
	 ('Air Terjun Tumpak Sewu Lumajang',2056,4.7,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT-kr1cTI8quImq_KUZkwteEh8gvI-UHSojUEpGsKL9t3Z7pXIyaqcWJo9kmjQ7npQ1IWJHwUbGGvRM5REUVc71aQ','jawa+timur','https://www.google.com/maps/search/?api=1&query=air+terjun+tumpak+sewu+lumajang'),
	 ('Bromo Tengger Semeru National Park',39373,4.8,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRADvbnAJsdfGRr06soEhE7Q5aTE2MIskP5mTrpB6zwbXuW6VwqEBXKeNktvqy-_HX4AuAxBZ1_hLqxypD535YIlg','jawa+timur','https://www.google.com/maps/search/?api=1&query=bromo+tengger+semeru+national+park'),
	 ('Baluran National Park',3455,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTSpIPbXU682HAPVRGJHz_2eHVj_x2A-gmMYBKfVbScMwElQt5d9qvIWN8245a4JWE08K47qQ8aHoMrYv5QJlIlrg','jawa+timur','https://www.google.com/maps/search/?api=1&query=baluran+national+park');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Prambanan Temple',76806,4.7,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS_5hZ-p4BFPiZ4aEy6xvUNpCU3q7IdJsQ_DFAy4merN6o1JJ1t6njEjKnU2VyxqH8Hcf4boCp2P08SvqsWE4OXxw','yogyakarta','https://www.google.com/maps/search/?api=1&query=prambanan+temple'),
	 ('Jalan Malioboro',3128,4.7,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRJJudah3m6m21W96KKk4jfLv1wcAOi3xzVL35WRcdwBTX7UwytNCzPYOnzdg0MIQg73U7CLVDDbYPzMW2aWaVLQg','yogyakarta','https://www.google.com/maps/search/?api=1&query=jalan+malioboro'),
	 ('Taman Sari',32619,4.6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQenzeJblg0hdJmOdwWX0rnEmV1W5sXSd28WbknkhhNPY6i0bpXu4vRYtYZJdxDf1iDpsF_xf7pu_E7Br2WPlS0WQ','yogyakarta','https://www.google.com/maps/search/?api=1&query=taman+sari'),
	 ('The Palace of Yogyakarta',32364,4.6,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRsu7cO4vaCvA5PJvn0_by-OIZoeHaNAD7W4JcEdv4sU68eYz_85IK0bfQR3ReWiKNipA4mYqvjhV2zlKIV9s2KCw','yogyakarta','https://www.google.com/maps/search/?api=1&query=the+palace+of+yogyakarta'),
	 ('Jomblang Cave',1086,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcROSq7Ozqdy9_TcBTrLObuLrc6Kxc1l02fnL-8wnAbobhwjd6FF_P9QH1e5Gplbe-NZyQapqeaB0pfqNSK2kAIJPw','yogyakarta','https://www.google.com/maps/search/?api=1&query=jomblang+cave'),
	 ('Ratu Boko',12675,4.6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ5LgGOPsJ-EWM8BAE8lDS9nHYGEOhufBfx-akMkqyiZjEM_ZOY2jWTfBo6Q3Gd2-1RmVTj0LmiZrdq85ao3FK_w','yogyakarta','https://www.google.com/maps/search/?api=1&query=ratu+boko'),
	 ('Komodo National Park',5030,4.7,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeFSqRt2Ftoq4LmGX8l_sbC-lRy7N-v48N6WvkDkki3pOZu2idVX8e-SLK10lH8cKCX7K732KWV6qVC0tnEJT_ZQ','ntt','https://www.google.com/maps/search/?api=1&query=komodo+national+park'),
	 ('Kelimutu',309,4.6,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQoVLTbS-9_UAIj5OHJGh6x629l8UbmEguydm-SuDOPn1g6ZfFDNhy1E6Rr3zcE-GNEQMqzHnErTjnFApGVsLYEpA','ntt','https://www.google.com/maps/search/?api=1&query=kelimutu'),
	 ('Pink Beach',1017,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTEEREdUqz5x_12X6UNFSvn2juONlxseGp7l2mkg27orvHiykmbydIUXcjPA-65KY-XOUR3vZyNvuvn9N3IN7ZHdg','ntt','https://www.google.com/maps/search/?api=1&query=pink+beach'),
	 ('Nihiwatu Beach',120,4.7,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRBkxstPdLewaf4mUoar6FXlR-arO_rtbY0HM8UaFAizSoUXO17Xwbz_Jc6WIRaozGy4p1yX-AUsoySqXITWuoBjQ','ntt','https://www.google.com/maps/search/?api=1&query=nihiwatu+beach');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Pulau Kelor',80,4.8,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRIlma7ib9cSQXZffmhemGFwS8ifLcIKNSIaCvh69Cq9W62Dm_OB4HVSmQJIXuhRtwkRO08to2iZjaSJ6c58t1xeg','ntt','https://www.google.com/maps/search/?api=1&query=pulau+kelor'),
	 ('Rangko Cave',573,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSMQAUbJdrnJputuPXZNzR-b6eRzCgwuhZsNSYHqh-DXxaoblyPMnUZiTKL2lPKSlcNqg9bxbVEvI1NfyU4ePJkoA','ntt','https://www.google.com/maps/search/?api=1&query=rangko+cave'),
	 ('Gili Islands',59,4.7,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR0MtDvPgDiTr2cpk-yFltSeyarvcEDgef-EoBmhzlZCcZm3Vb1HJiJcvX_x-5VnR2GdV-PbkFZCGJ1Pw8spyp_ow','ntb','https://www.google.com/maps/search/?api=1&query=gili+islands'),
	 ('Gili Trawangan',2165,4.6,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTgGeDKBFo9fQdZXRNMAKFkayogar1cBQwa1RZSmiiM_2xJw--sUIWOOYxxmuxZCdubzNnclKrgNEK67AyCkHc5iQ','ntb','https://www.google.com/maps/search/?api=1&query=gili+trawangan'),
	 ('Mount Rinjani',1965,4.5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOsDy2rgpcreS0qdL8EC648CUBEa3eP1-iXv3XcwT5W9k6ZsY_wZO62k8IYa0AG9WoqM-r16qS_dYxSrcTwYqvLA','ntb','https://www.google.com/maps/search/?api=1&query=mount+rinjani'),
	 ('Gili Meno island',301,4.5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvFu7BBuwStXOOOE91wXwcBo9dpEMa-eRGaG6yfFp2ixOr2cdnX7rmzf9e4iSrdNC7u2IgWQYo112cKkE1jB8Y0w','ntb','https://www.google.com/maps/search/?api=1&query=gili+meno+island'),
	 ('Gili Air',621,4.4,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRWXZ1Yqxaq8u1gLsRTbmP0e3daAyNsNIBvxa9JZ_T7rqfo9jbRz0_N6LjnvokKIIjZQLLA7MmOZHaksmN2TIgwAA','ntb','https://www.google.com/maps/search/?api=1&query=gili+air'),
	 ('Pink Beach',1824,4.2,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQWgc1sIy5eaDxmxpNoEjw1_JbZScBsXSCKbfWOY-lSXZT8R1koXOE5rqEudvOKMExsVrX_LlH9J8T7NgA7srfRIw','ntb','https://www.google.com/maps/search/?api=1&query=pink+beach'),
	 ('Uluwatu Temple',27513,4.6,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSE1kRrTRO4EHffO2KAtIVXrwwDpefD-r2FM0PA2Iv9u3IEq6NNLjtsuuFz56Iifoe9vr8sLpNbSg56SJ-5PCI4yg','bali','https://www.google.com/maps/search/?api=1&query=uluwatu+temple'),
	 ('Sacred Monkey Forest Sanctuary',34510,4.5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb_4T8EtyOI2FKSHNIAOgXQpMYnIRfQRtGejL4gL56k4BoIp9Palt1rg4A9FJgWGOoMdOlMUGtKJZTVLRoAq6Jxg','bali','https://www.google.com/maps/search/?api=1&query=sacred+monkey+forest+sanctuary');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Seminyak',31992,4.4,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQrQCYOYckLAoT-Rk3IQjiZUbkOTEobcY8r2syrIaxsuNNhv_IONYVSLg0rqcw76DJObo9iX2fqEclowieLrOukPQ','bali','https://www.google.com/maps/search/?api=1&query=seminyak'),
	 ('Tegallalang Rice Terrace',26615,4.7,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRJYbefdedPZ0l2Huo5vzTlYGGJe2ueRkwfBWQgwYpmwuI4v8oO70TjoShm41uxiTpFTIAfPJf04jhDGnvIlA9zYA','bali','https://www.google.com/maps/search/?api=1&query=tegallalang+rice+terrace'),
	 ('Ulun Danu Beratan Temple',2327,4.6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP-08wYK3_IAnR8vio9GrWcdEne_Kd3bU9li18yCd_ORZS7e4EJ7jHsJbioW7UgKtlAM12a09EG2XUdznaiy1_tQ','bali','https://www.google.com/maps/search/?api=1&query=ulun+danu+beratan+temple'),
	 ('Mount Batur',4332,4.5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOWdSruDX0qFbhsgaakAyvfWJFLEW6Kf4NGO1WwjpL5whOzM6uVrYhbfKXpBMwwzlvT9dTzrDbxU8l-htQPFR62Q','bali','https://www.google.com/maps/search/?api=1&query=mount+batur'),
	 ('Derawan Islands',283,4.7,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSUBmP3ozTtLGz2sOFY1w9xyxUlWOldIfd3cGDFkEXm0etdn2a5BfUWk3YPA-KuQ22qW7dVUdXwd7qkk4ITZ1rfZw','kalimantan+timur','https://www.google.com/maps/search/?api=1&query=derawan+islands'),
	 ('Sangalaki Island',183,4.7,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcToN04H7_FqY6EIB99-Of1hRcUQhIZuzucwnPweWecvjoK964iDOgMB97p-7-bqOyu5mTu6PnrTIJfLP8x7gr-mQw','kalimantan+timur','https://www.google.com/maps/search/?api=1&query=sangalaki+island'),
	 ('Kemala Beach',3537,4.3,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRfTGIlBjuaQIqYKUnRu0hwf6UXPruhRX0El7L2zS6L2MGcC2gkW6Uw3SNChgY9SR0IP1wZzwkQsyAZrQu3crGwqQ','kalimantan+timur','https://www.google.com/maps/search/?api=1&query=kemala+beach'),
	 ('Lamaru Beach',2606,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQW_OQns5C5ZPO55Yp-5EtfFfWfsnIiit7pRhrLLnUYP-5CTKBKCq2w8zZmwjdIDtOJwuuRVciRK0IG5riWXbV00A','kalimantan+timur','https://www.google.com/maps/search/?api=1&query=lamaru+beach'),
	 ('Islamic Center Mosque Samarinda',3219,4.8,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQBFtlIsj8glrSiZ5Pc3AwQv65YzQUW83NsMqpucmhbM0GyNdxpZ7BZjqFAma8hTVv6O55u3dfKdFVwvAjTcLfo-Q','kalimantan+timur','https://www.google.com/maps/search/?api=1&query=islamic+center+mosque+samarinda'),
	 ('Pantai Banua Patra',1079,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRS6ODFTGFSYJYEVanC0TNs-iqPv5-B_h-G_qFez0gO9-HiwapPBu9os1SS3HGJXRcKw0RS4MfdfDgH4MhP1BM7-A','kalimantan+timur','https://www.google.com/maps/search/?api=1&query=pantai+banua+patra');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Taman Nasional Tanjung Puting',832,4.6,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRL_D2UP2iwgHLXf-GGYp3HynndRoqKXod4DOZCnUBEcogHiApLdxgpOeQaG8VDSXTMhQEKTOWYGB7sSX0S5jhoVQ','kalimantan+tengah','https://www.google.com/maps/search/?api=1&query=taman+nasional+tanjung+puting'),
	 ('Sebangau National Park',2008,4.2,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQtN1-PnCxATI5LnTV2r_lXwPD01MQZcfK6Fb97DquJeGjla0AsioYRdyb6AhYnGnIATNw7JN7Jly0qL3SPWLyvOQ','kalimantan+tengah','https://www.google.com/maps/search/?api=1&query=sebangau+national+park'),
	 ('Pondok Tanggui',24,4.9,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTIokGUdexrTJ8-hBkyaweGOv4-tymN9UB0d5kxwBAySgwo5xzmtNvyIxRerTe3ctDORTrvBymnRtCOQKyfKaLIDw','kalimantan+tengah','https://www.google.com/maps/search/?api=1&query=pondok+tanggui'),
	 ('Sekonyer River',4,4.8,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRTqkQ0pTj69Zi-BNsZ9J28MEuTAyPiqGDsdzbuLNeRGC5u75DYJl9RvmTX2eJEUS-rEJ2aCKlg7l7wHkobKKtpWQ','kalimantan+tengah','https://www.google.com/maps/search/?api=1&query=sekonyer+river'),
	 ('Dermaga Kereng Bangkirai',3051,4.3,'https://lh5.googleusercontent.com/p/AF1QipPYlnwpn8K9Kk4t6S_SERMxyrBqnSLec44PZfLR=w464-h260-n-k-no','kalimantan+tengah','https://www.google.com/maps/search/?api=1&query=dermaga+kereng+bangkirai'),
	 ('Museum Balanga',394,4.3,'https://lh5.googleusercontent.com/p/AF1QipPP8Kdx4GdGVx1ZINtiGhP7AkC4S3_HavSf7wlM=w464-h260-n-k-no','kalimantan+tengah','https://www.google.com/maps/search/?api=1&query=museum+balanga'),
	 ('Lok Baintan Floating Market',727,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQxCaJ1WSl9ZfROMS1452BdbOqCKIrwmDumHDF2SdjTuvnW4bKxFQ6kWQtI9dDkfmjqSqktOLgOvemsVnAkMJkpJw','kalimantan+selatan','https://www.google.com/maps/search/?api=1&query=lok+baintan+floating+market'),
	 ('Bukit Matang Kaladan',1977,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSbvKXyPisOX3A09isKf2qV2uqJTm8OVQDOok7OQvOct3Iv-OJZqnZ8PKtZCON_btWXE26Bj56zKmxGRenR2idtiw','kalimantan+selatan','https://www.google.com/maps/search/?api=1&query=bukit+matang+kaladan'),
	 ('Angsana Beach',1518,4.2,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTWDIkar3_H09LVjttzBSs10YRU1_uMwVzLmD5efr5dDubWskokfxVYg8TjBJ_J_lCUp2Stkv0Ga12CEUnwxr1q-A','kalimantan+selatan','https://www.google.com/maps/search/?api=1&query=angsana+beach'),
	 ('Takisung Beach',2778,4.1,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRfNcb_MWQrEfVpSZbleOA-Kj8SM3ZnEFZW1eRbrMsYax07_2tFWotxlcYmm5N420pdUzg7u86Q3l0oD-csx0zDwg','kalimantan+selatan','https://www.google.com/maps/search/?api=1&query=takisung+beach');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Riam Kanan Reservoir',181,4.3,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRkCG1-qBC6n33fcpT07Lh3rEUreAgYx5tRrCMZtazWSWghxOe7Y4r78yJ2FJYdsWEW4riTFkuwIiDyvCpp6BD7Fw','kalimantan+selatan','https://www.google.com/maps/search/?api=1&query=riam+kanan+reservoir'),
	 ('Bukit Batu Langara',262,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRvF9SnSK1C89SNYpg39YS9XLnFi87skEv1O1zPw_sy98TfldGH83Ur-FaFyqBPDKlTMoBswILrM6xEIe7fEklU8w','kalimantan+selatan','https://www.google.com/maps/search/?api=1&query=bukit+batu+langara'),
	 ('Kayan Mentarang National Park',246,4.3,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRl0kkBni29fWbiZXBFPqdN8qFin6rKhGI1WOo_1o-uDI6Z8bFeqxRxinh1iZTS0j6k6eTVOwzXVKIo_Zffet4VoA','kalimantan+utara','https://www.google.com/maps/search/?api=1&query=kayan+mentarang+national+park'),
	 ('Pasar Inpres Kebun Sayur',9802,4.4,'https://lh5.googleusercontent.com/p/AF1QipON3uNknl2VhDsM4SLY9aNQQ9jPt8IJso7nvn5v=w464-h260-n-k-no','kalimantan+utara','https://www.google.com/maps/search/?api=1&query=pasar+inpres+kebun+sayur'),
	 ('Kawasan Konservasi Mangrove Dan Bekantan',2227,4.3,'https://lh5.googleusercontent.com/p/AF1QipPF0rSRIIJIo8gNKkt--KJwVgZNzcTLe0sushYN=w464-h260-n-k-no','kalimantan+utara','https://www.google.com/maps/search/?api=1&query=kawasan+konservasi+mangrove+dan+bekantan'),
	 ('Attractions Niagara Mount Rian',141,4.3,'https://lh5.googleusercontent.com/p/AF1QipML65-5HqDceaor6JLCrZ4hv0v_NNgyADL0qK00=w464-h260-n-k-no','kalimantan+utara','https://www.google.com/maps/search/?api=1&query=attractions+niagara+mount+rian'),
	 ('Semolon Waterfall',36,4.4,'https://lh5.googleusercontent.com/p/AF1QipP2Wb7QG3iPbZ6zYOjZwPhT0mRtPfHUvl1ij2Ak=w464-h260-n-k-no','kalimantan+utara','https://www.google.com/maps/search/?api=1&query=semolon+waterfall'),
	 ('Museum Rumah Bundar Tarakan',163,4.3,'https://lh5.googleusercontent.com/p/AF1QipMM9QRJHAGpOZnm2Tnv2-fLWWnHQeQnD7g2Vtnp=w464-h260-n-k-no','kalimantan+utara','https://www.google.com/maps/search/?api=1&query=museum+rumah+bundar+tarakan'),
	 ('Khatulistiwa Park',7156,4.4,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQqQ6Z7Iv0i28pDvtX4mgDTpoIKgPPtg39bASe3yXOB0TZBw_xsCq6J4Zrnt799FBIimEAEHoAvlKmaQT3xNC4x0A','kalimantan+barat','https://www.google.com/maps/search/?api=1&query=khatulistiwa+park'),
	 ('Pasir Panjang Beach',603,4.3,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcS7rlHrrNDK4I6UjdBDehrTUYB5beQP9bovIfZN2h6Zp21yAZ_uraf0TmZ1nNonklg-2NCvlqRHgDTNaUEEKXdLeQ','kalimantan+barat','https://www.google.com/maps/search/?api=1&query=pasir+panjang+beach');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Lake Sentarum National Park',345,4.6,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR6IV3Qfz8oBzWsutTS1L09vbVxFpbTJ04E8-hplUBgVCWsbIRgu1btzIQAh3gfzB4tvptCjdzTanGGQwHTRJLVzA','kalimantan+barat','https://www.google.com/maps/search/?api=1&query=lake+sentarum+national+park'),
	 ('Mount Palung National Park',140,4.1,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR5ShViVqwg3onWrdEopdwps4t3V2vbIcrt6ITabKYzaUOY-LhudxW4R06Dc0DfNRLvNOyd6ddQFiVymruudjSTNA','kalimantan+barat','https://www.google.com/maps/search/?api=1&query=mount+palung+national+park'),
	 ('Mount Kelam',109,4.5,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcT6LQoV1qUF4Rq_FFba9yP_Vy95YiD2KCkth9ChTh3oV-3g4o5eyjwVQHxYTp72qlUJ19E5wljbZ1d9tQ2lFEbe3w','kalimantan+barat','https://www.google.com/maps/search/?api=1&query=mount+kelam'),
	 ('Kura Kura Beach',687,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSh1iUGg3lBuLMDBQYWTrTQ7xTuSXaQvkOcReH1jxvOEO7PDEhgie0QnzBh_WL0EHIWamcN2nuWdNL8VSxsyEb_RQ','kalimantan+barat','https://www.google.com/maps/search/?api=1&query=kura+kura+beach'),
	 ('Bunaken',318,4.5,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRteuL8ESUj2Ne_neux-Tm9QozDYekQx5s6dJ-eFTwdbDJO1HDSwXmHJrqTa-Uq6Z4CnoxXTl5rPpB_Ke_qo9TsnQ','sulawesi+utara','https://www.google.com/maps/search/?api=1&query=bunaken'),
	 ('Bunaken National Marine Park',2803,4.6,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSdApHUL_ZSlN-A_PuKADslqV6xtTLfNfJOD0iaIj9TN9ZWGwfGwmdCOj7w-g1t7XqwcgamchQFElniZ_fp6LjFZw','sulawesi+utara','https://www.google.com/maps/search/?api=1&query=bunaken+national+marine+park'),
	 ('Tangkoko Batuangus Nature Reserve',29,4.3,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTPcaWZTCGP_oN_vL0-2IlEDNT_A08h59inEZypUB5B85OCzyHTMWzNwyvYjm9QTJvG4LhqL1iDUSYUukh1NI_kfA','sulawesi+utara','https://www.google.com/maps/search/?api=1&query=tangkoko+batuangus+nature+reserve'),
	 ('Siladen Island',60,4.7,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcReT6b6EqmFnOFMZ7LI8iLKTKYV598femMVPoXb6NBRzBvlq6x0JmAMYhtGu9Ps4K3XiD8yttb9FSBGQpSmIKT0_A','sulawesi+utara','https://www.google.com/maps/search/?api=1&query=siladen+island'),
	 ('Lake Linow',646,4.7,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTrb6H3bRHO4ZGG8jKs6nJ--V2t_9MF9epkYLuP01kOUq9ZnkRjqO51CvL_vRvRTMxgYmCiqyG84N0LS952-_NUxw','sulawesi+utara','https://www.google.com/maps/search/?api=1&query=lake+linow'),
	 ('Lake Tondano',347,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSNRPRrSXc-24W8lky7NWRoU0EWhoVJPDoEgjRcunMlmm2ZERT9OX0hmdp20zDj5e4bnZB6CF7jdLFzLJzE9v1A_A','sulawesi+utara','https://www.google.com/maps/search/?api=1&query=lake+tondano');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Losari Beach',2962,4.5,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRBS7OluoMo0PKYH38q_EjXW9t2TWQkyRGGS2Ers8VsQFimHy614gPNyORAnRBWGfcPGxzTeHYbV9FMapamQRS3mA','sulawesi+selatan','https://www.google.com/maps/search/?api=1&query=losari+beach'),
	 ('Fort Rotterdam Makassar',11754,4.5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzJrqSeN4zpICQg6CAbds2COCGySShD0FO1DG1n4r8r3CGqB9ESbdxqbG4gMN2Ip5y6EcxdZROnxGnhYJNQ-ouiA','sulawesi+selatan','https://www.google.com/maps/search/?api=1&query=fort+rotterdam+makassar'),
	 ('Tanjung Bira Beach',1800,4.6,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQ1eyJpoNEH1XjdAb_hMrj9fbVsue1_0SEaQBJsr6RjiU1brXJ_3iimLQE6hVt68iLsniyZv1j5Lkmuq49107LWiQ','sulawesi+selatan','https://www.google.com/maps/search/?api=1&query=tanjung+bira+beach'),
	 ('Mount Latimojong',334,4.4,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRlXf1iAbSuiHJgXLKTWZSdEIq80BrbpnR5LpLYKQaKDvvyoe2--MzZY-dGWa0k7zGJglhxlGDSHSJWpQ','sulawesi+selatan','https://www.google.com/maps/search/?api=1&query=mount+latimojong'),
	 ('Samalona Island',297,4.5,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQilYoN9_nbQipYvnXY9PjCkrNh22iatXz7qhzTXHEdRFvKn9UJ9_LsAmSYmRlJ4_bUEPpttI5MnkO1Fo2NrdHlRg','sulawesi+selatan','https://www.google.com/maps/search/?api=1&query=samalona+island'),
	 ('Taka Bonerate National Park',94,4.7,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcROZ5C__A5gOKDXbXB1RJgGU-KrZrHzGjZ0UnUVA72XrFDlpDIq0gsMpx-Pbeq3Y72ML2IJQeH9s3o9a7Y0UhiFAA','sulawesi+selatan','https://www.google.com/maps/search/?api=1&query=taka+bonerate+national+park'),
	 ('Pantai Mampie',194,4.0,'https://lh5.googleusercontent.com/p/AF1QipNoYZBdnJmFMtFNkNiP2yI9iUeqKfNXrZDQHrIl=w464-h260-n-k-no','sulawesi+barat','https://www.google.com/maps/search/?api=1&query=pantai+mampie'),
	 ('Pantai Dato',1035,4.5,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS2wOIjyHSvLLIvRSO1OL4KA1k2Cn3Zpa_5biGUPbPiqdI-ys1LT9P6fBDmgQAhXcpK8ME3lvmgyANiysC1HTzW9g','sulawesi+barat','https://www.google.com/maps/search/?api=1&query=pantai+dato'),
	 ('Pulau Karampuang',57,4.5,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTGp0iMr9vWejBort2IuyiFPBUuZyw2TGN-ifZWTScGg1o7ct70lPhj0Nk2DgGZ02MfBwAnL8k1gICIag','sulawesi+barat','https://www.google.com/maps/search/?api=1&query=pulau+karampuang'),
	 ('Pantai Palippis',167,4.2,'https://lh5.googleusercontent.com/p/AF1QipNc3UW2jim2IM5zDRCc8gGXlJEHRDo2rhxobuM=w464-h260-n-k-no','sulawesi+barat','https://www.google.com/maps/search/?api=1&query=pantai+palippis');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Pantai Lombang Lombang',247,4.1,'https://lh5.googleusercontent.com/p/AF1QipOSMArHQTHSstE4SGHqA28iQ4bXYnZ_4T4yN_Xn=w464-h260-n-k-no','sulawesi+barat','https://www.google.com/maps/search/?api=1&query=pantai+lombang+lombang'),
	 ('Air Terjun Tammasapi',87,4.3,'https://lh5.googleusercontent.com/p/AF1QipMbDT42XmGC-YdhMntFO7RPoO07511bqwqKSNBt=w464-h260-n-k-no','sulawesi+barat','https://www.google.com/maps/search/?api=1&query=air+terjun+tammasapi'),
	 ('Lore Lindu National Park',96,4.3,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcT4B-WkxBKE2z-kNoiuLD_oXER-m2cI2BhBUZK0KQabIkp5EXFZ4SsJV3oDFgMYoMtqREbIZOSmOg28GYfzsf6QNA','sulawesi+tengah','https://www.google.com/maps/search/?api=1&query=lore+lindu+national+park'),
	 ('Pulau Sombori',146,4.7,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSjAyQ7zkZ2xABVUsw5wloF7ITIEWIU8Mk6VAnv8wg_qqajbThZs9QpceXGl3aFmisp0oKb4wGFUUTcSJYxTJVp6A','sulawesi+tengah','https://www.google.com/maps/search/?api=1&query=pulau+sombori'),
	 ('Pulau Kadidi',1,5.0,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRpNkgAUgXCGtdEiYBeyY35ekTUHJYoCdpGFGn0zF5eADUzaOVoCAziADeoGyL1bnsqqY2w-QQS0u36xRMGXgxsyA','sulawesi+tengah','https://www.google.com/maps/search/?api=1&query=pulau+kadidi'),
	 ('Pusat Laut Donggala',445,4.4,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSb7z-zGwEOCFHGo3--faUFqL5aoezKzSOLhmp0_7vecqJvbUdg-bIfry_5rFaNqeJRujUSc8i5C8CzKxnFsvG2tQ','sulawesi+tengah','https://www.google.com/maps/search/?api=1&query=pusat+laut+donggala'),
	 ('Tanjung Karang',26,4.3,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSnrBC-V2LogDGhCG4oqELUX-LuevyxBlRcDu-WcxmA0S57LCoM-KDY2768drYCheedqQf1DooJFmuqx3GNV-vwHw','sulawesi+tengah','https://www.google.com/maps/search/?api=1&query=tanjung+karang'),
	 ('Kepulauan Togean National Park',470,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTBkZGZHXi7BBLtb0FKi7ordAXqspIGz6ApEtI_ZZtYR-Is5Z1z5Zw-KUJhHsABN11txsgseQ5dLWgRH3l6YhMZfQ','sulawesi+tengah','https://www.google.com/maps/search/?api=1&query=kepulauan+togean+national+park'),
	 ('Wakatobi National Park',2028,4.5,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTW7KhS3Vn4D0nEhGntQJwJ1GV0tZbPISQkoPZxEGuwHejf3_8PBK6aQyf6uc1IENJKayx0RRgNJXEXru9-JVD8_g','sulawesi+tenggara','https://www.google.com/maps/search/?api=1&query=wakatobi+national+park'),
	 ('Nirwana Beach',1019,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQA4P9Ufb9dhlgKpZ5QcD0w87BClfcTr0SkTfhql-_nUGADpdA5rPiKQ3OV65fNVVjQQDX_5RC80hk50up9lgNLCQ','sulawesi+tenggara','https://www.google.com/maps/search/?api=1&query=nirwana+beach');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Pulau Hoga',39,4.6,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTwLJfbnaV7PbHCKnNCY6pRz8OOgjhht3vTdwuu7OrCHTQ0zNIe2FPgezrqCJG64eJ6H9MenYpYhCWwDJ0MDlEwdw','sulawesi+tenggara','https://www.google.com/maps/search/?api=1&query=pulau+hoga'),
	 ('Buton Sultanate Palace Fortress',1174,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSUhki1hEbLKZB2u9E4mzRFrLlT0DBJGxf84fUz_QIO2qQIUaYfeEgK7L_IvDv0APvuYGa9A9QjvnS6jNH6_NuLRg','sulawesi+tenggara','https://www.google.com/maps/search/?api=1&query=buton+sultanate+palace+fortress'),
	 ('Pantai Toronipa',643,4.3,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR7fion_vKkLuwe-080RhsSR0n6VozDS5PDY99geGahs2Z6MXlfg08bsPM9sxsmoH5N7lY-pTLnhwaxHg','sulawesi+tenggara','https://www.google.com/maps/search/?api=1&query=pantai+toronipa'),
	 ('Danau Biru',884,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTzO3D3JDnIQtvRgo7POJ6Ewm5_J8NbO1By1FthMuD5g70fFc_l8R0fi8MEB0sc3Li_uQCnRnvmhLWaA4X03Jx56w','sulawesi+tenggara','https://www.google.com/maps/search/?api=1&query=danau+biru'),
	 ('Benteng Otanaha',1760,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQMGNlzNw7W4JGuHD5qOa5aOVXFWH7D7NPeSWlPuikPT-OYyehO3BTLgA9my2BZW7k8rGfMzjD1yKJAQAwSMMDzDA','gorontalo','https://www.google.com/maps/search/?api=1&query=benteng+otanaha'),
	 ('Bulalo Limboto',100,4.2,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSqt7bCbQ41AwjYsFuX_Ox6xUmh74ZNXv3wbByEOAQfPD2IiTCu1F5lCJzgR4PVxPzM7075x5XWK4nvL8Tr0G8R-A','gorontalo','https://www.google.com/maps/search/?api=1&query=bulalo+limboto'),
	 ('Pantai Kurenai',971,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSycNENxtU1jQ86FyBOH93H5ntrCLcpL-LiN8CW0AOFnaCu5akFut4p4woPFHcNVpWWXBEOpFwVgHNy-BEUuCnEoA','gorontalo','https://www.google.com/maps/search/?api=1&query=pantai+kurenai'),
	 ('Taman Laut Olele',705,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSdzS7ubG9UyRn5-GqqboyEiljqPLaWLAz1GHvm7dnJrNslMP3g9GcIvWRgt3nmcxIlr5pirocbWBygnsDJisHOCQ','gorontalo','https://www.google.com/maps/search/?api=1&query=taman+laut+olele'),
	 ('Wisata Hiu Paus Botubarani',451,4.6,'https://lh5.googleusercontent.com/p/AF1QipMSl39Xq2WUJnwUwcy7oeqhYneEFro_18kfOBBI=w464-h260-n-k-no','gorontalo','https://www.google.com/maps/search/?api=1&query=wisata+hiu+paus+botubarani'),
	 ('Masjid Walima Emas',164,4.5,'https://lh5.googleusercontent.com/p/AF1QipOo7KD8PcyTkgCPcmEyDGfB5JWijqz1rff7vjgi=w464-h260-n-k-no','gorontalo','https://www.google.com/maps/search/?api=1&query=masjid+walima+emas');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Banda',61,4.8,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQpBduWazbn4zhT2wbuuyPWy1E_05DfZSYJfdJ0l19BXkEI-e4hih8wg8xIOxFrYs92TstQJAsd9gRpn-R9pMbSkA','maluku','https://www.google.com/maps/search/?api=1&query=banda'),
	 ('Naira Island',70,4.6,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRj5aQVM6QEV64ZOtSMuA092SXc55BmDk6hf6gYap6k5si8JPJgdpBjdUTq72x3_NrkdPsxmyj3czh1SdyV3XK7Ww','maluku','https://www.google.com/maps/search/?api=1&query=naira+island'),
	 ('Natsepa Beach',2083,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRP0tEgfCOUPsrD-S6yVaiPtRRzZDKFqycikGiSYhmnamlTJVMcDFzO_PV7obtRcCzk33tAuY3XOilzRRWa7r50eQ','maluku','https://www.google.com/maps/search/?api=1&query=natsepa+beach'),
	 ('Pintu Kota Beach',850,4.4,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRklQN7uA-DgMnOyQVw0baCOgS5MKuDKCnjZg1iPox-1ujCFmCn8mZFXyXG-16xnp_-hwMYeLOa1c1jaDST2g8FFQ','maluku','https://www.google.com/maps/search/?api=1&query=pintu+kota+beach'),
	 ('Mount Binaiya',32,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRZy1fpaJlNxvRuo_kBuSXtnlFgDv33_8JrW5RwGd88vtkohuHjPkNU5Z6NCyiYCho99ADekD4mJ9rOSHjWaSbxiA','maluku','https://www.google.com/maps/search/?api=1&query=mount+binaiya'),
	 ('Manusela National Park',59,4.3,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTbX6YoegVgT1L8E7dHNmsgaPMnt9fCDNruFtVOK8v3igZ1d0ykKNuPzX7ggXISWZdhRVKW6oC1XeobJg9qCVCdKw','maluku','https://www.google.com/maps/search/?api=1&query=manusela+national+park'),
	 ('Sulamadaha Beach',469,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSRqGf2fxRtobH7-jbUle1gX2onLbEP3ocLz_wQvyLZVog1wlPiYrq2JH5IYnbwjei_onomCTfq392eDu4n_NVcNA','maluku+utara','https://www.google.com/maps/search/?api=1&query=sulamadaha+beach'),
	 ('Gamalama',221,4.3,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSoAue5Y4raE3Z39JxhzhL1trDUwieqVoNTFIbYFWGZvOEMd3zOI2YuTmQDgQa5Ad64EeBMeNiFEx0J5beE9epV7Q','maluku+utara','https://www.google.com/maps/search/?api=1&query=gamalama'),
	 ('Danau Tolire Besar',135,4.7,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRPHNdUxH3Aq3yQiipVcjgSEkid1oqWdC3qSOtXZKEUO1VCXqgQmc7kVV1ErCC0XLrdMaNrwch0Ai_cyvZWGm3Ofw','maluku+utara','https://www.google.com/maps/search/?api=1&query=danau+tolire+besar'),
	 ('Pantai Jikomalamo',1643,4.6,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcS0fHR5ihKCEwI9xKtOGwf-IFeZbAh0AsngMjgQOF5vaEUsDLKl5snoNKIYYDIHgfwNK4vkpUlHAI8UMUs1r78iLA','maluku+utara','https://www.google.com/maps/search/?api=1&query=pantai+jikomalamo');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Benteng Tolukko',846,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQ2YyAO0C6YMHuQgdkpR0HlOe0mJJxSOzPdfEgJr6pnQ1hdfjjWlElkx6VY3rShz2I3VDLrLrpfGkycSdBiuxA3sQ','maluku+utara','https://www.google.com/maps/search/?api=1&query=benteng+tolukko'),
	 ('Benteng Kalamata',603,4.4,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQa2rkEgTW5ZHhxEYHb0r0Th8Htz1dLwwoCkTryL4PcKhiymQtJsRViEQ5LzbUbX-Kn5u0z3-h616-E_hKa23N0dg','maluku+utara','https://www.google.com/maps/search/?api=1&query=benteng+kalamata'),
	 ('Puncak Jaya',729,4.5,'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQKcsH-ivO1Rij8Ugkp3_NXNFZ2xcWGskMR0TpYZZoVbtyv5wkxsxXosORsFvkRbD3jEH0NKKJHE0cS1RroVWMPTw','papua','https://www.google.com/maps/search/?api=1&query=puncak+jaya'),
	 ('Lorentz National Park',325,4.4,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSL8REKMi8ZIZ_BApSWlYiTrZF4rm_OaPU3IWfRYBRg8Pj24jLbpPf3SLk4DM-3PomLuOhXBfBMPn4_4eHhUtPdSw','papua','https://www.google.com/maps/search/?api=1&query=lorentz+national+park'),
	 ('Harlen Beach',221,4.6,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRQg_EMl6Hg5h0bOXriDmn749T2bgc7l-3TEO28QVLWKvvMdMsE3rmywA_EePbKmFjW1G7y23GOD17okg','papua','https://www.google.com/maps/search/?api=1&query=harlen+beach'),
	 ('Base-G Beach',1040,4.3,'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTn5_Qes3HCuOW8ftgrWBssiqDgJc_qfc0RS40z3TL6sqhzPXGS-Fx1AQl_3NBU4MJbU8s2N_GyaKg2GVH3qwCtUw','papua','https://www.google.com/maps/search/?api=1&query=base-g+beach'),
	 ('Wasur National Park',43,4.0,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQVJvf-2OffmrpSZRVOYnF6jLIKUImj0uMxgkSkLcMuBYx9o3Mku-CVHhBCd4oox8iD1KzYXucQXajpCG9XKGKZ4Q','papua','https://www.google.com/maps/search/?api=1&query=wasur+national+park'),
	 ('Holtekamp Beach',166,4.3,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRk6m9WQZGLLWDf8apb5UTwAHe43WYCB4NVNuu5sXahLWTVVb5W_wQxCUIPs8xF0VzqgizCvnyB5y0mwg','papua','https://www.google.com/maps/search/?api=1&query=holtekamp+beach'),
	 ('Piaynemo Raja Ampat',1578,4.8,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTbAIZdbyv67zXuJh5B16Aww2G8Lj6KjbHblS3G3MjgjtuDtGMv0pHu7DWeM6Ed3nh3OSNei3mt8V0pOqRgb7Ymjg','papua+barat','https://www.google.com/maps/search/?api=1&query=piaynemo+raja+ampat'),
	 ('Kri',62,4.7,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcS_6jPkKu2pZy8_o9yhmMRy6cDV8kgUhoXBBn_xyK4MbV8Q4ivVQZ7y8SIlA00ydbu6RigQM0mFDAjl0Nxrcu37Tw','papua+barat','https://www.google.com/maps/search/?api=1&query=kri');
INSERT INTO posts (name,rating_total,rating_score,image_url,location,location_url) VALUES
	 ('Pulau Yeben',3,4.7,'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcR9a_gOMc_Crf4PZlshPbLSOvqbM-VRTHHEPJrPk31MHE7I3BRcfHsseE27aRUmTeD7jJ8eaxutWn7zXDapN9g2Ng','papua+barat','https://www.google.com/maps/search/?api=1&query=pulau+yeben'),
	 ('Mansinam Island',59,4.5,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR6LbubKdAdBGqoEMiJIKTOlPIIlkt0n7jX_KMXMhp8lvFAtyHRedQOSXA0_R39DMjAMADw8PrchFTnRqry3BBF_w','papua+barat','https://www.google.com/maps/search/?api=1&query=mansinam+island'),
	 ('Sauwandarek Village',166,4.7,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSoPQfFfma8OOl2e4rn5BCQfQ-YUNDD0BDnsLL5dLn6i5NTo-1ArW1mPa0m-7J9m1nP1N--SvN6UM3PVN1Y23-23g','papua+barat','https://www.google.com/maps/search/?api=1&query=sauwandarek+village'),
	 ('Gam',8,5.0,'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRtX3LMw401AsLD63PB6oOG2BtVzRDPBGrK-pOa1CRK1lTnLuTpuTkKn7-JIsO3tCnugRFk_PJU_qRHb97xHhkvkQ','papua+barat','https://www.google.com/maps/search/?api=1&query=gam');